In [50]:
import numpy as np
from sklearn import preprocessing

In [51]:
#设立处理的数据
data = np.array([[3,-1.5,2,-5.4],[0,4,-0.3,2.1],[1,3.3,-1.9,-4.3]])


# 均值移除

In [52]:
 #保证特征均值为0
#将数据进行缩放  公式为 (X-Mean)/Std 中心化数据
data_standardized = preprocessing.scale(data)
print(data)
print(data_standardized)
print('\nMean = ',data_standardized.mean(axis=0))
print("\nStd deviation = ",data_standardized.std(axis=0))

[[ 3.  -1.5  2.  -5.4]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]
[[ 1.33630621 -1.40451644  1.29110641 -0.86687558]
 [-1.06904497  0.84543708 -0.14577008  1.40111286]
 [-0.26726124  0.55907936 -1.14533633 -0.53423728]]

Mean =  [ 5.55111512e-17 -1.11022302e-16 -7.40148683e-17 -7.40148683e-17]

Std deviation =  [1. 1. 1. 1.]


# 范围缩放

In [62]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print("Min max scaled data =\n", data_scaled )

Min max scaled data =
 [[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 0.         0.14666667]]


# 正则化（归一化）

In [64]:
data_normalized = preprocessing.normalize(data, norm='l1')
print("\nL1 normalized data =\n", data_normalized)


L1 normalized data =
 [[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


# 二值化

In [67]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print("Binarized data = \n",data_binarized)

Binarized data = 
 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]
